name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run backend tests
      working-directory: backend
      run: |
        source venv/bin/activate
        pytest tests/

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Run frontend build
      working-directory: frontend
      run: npm run build

