name: CI Pipeline

on:
  push:
<<<<<<< HEAD
    branches: [ develop, feature/** ]
  pull_request:
    branches: [ main ]
=======
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - main
>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7

jobs:
  build-and-test:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

=======
>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
<<<<<<< HEAD
          python-version: '3.12'
=======
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7

      - name: Install backend dependencies
        run: |
          cd backend
<<<<<<< HEAD
          python -m venv venv
          source venv/bin/activate
=======
          python -m pip install --upgrade pip
>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
<<<<<<< HEAD
          source venv/bin/activate
          pytest tests/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
=======
          PYTHONPATH=. pytest
>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

<<<<<<< HEAD
      - name: Run frontend build (to validate)
        run: |
          cd frontend
          npm run build
=======
      - name: Build frontend
        run: |
          cd frontend
          npm run build

>>>>>>> 9b0ad7e257c8a7a075c4dab0a3aba57ec30bbcd7
