name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # IMPORTANT: These should reference GitHub Secrets, NOT actual keys
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ensure this matches your AWS region

      - name: Deploy backend service to ECS
        run: |
          aws ecs update-service \
            --cluster devops-ecs-cluster \
            --service backend-service \
            --force-new-deployment \
            --region us-east-1

      - name: Deploy frontend service to ECS
        run: |
          aws ecs update-service \
            --cluster devops-ecs-cluster \
            --service frontend-service \
            --force-new-deployment \
            --region us-east-1
